# Project information
site_name: "Havenstad Documentatie"
site_description: "OfficiÃ«le documentatie voor Havenstad, een Fivem Roleplay server"
site_author: "Bedar"
# site_url: "https://192.168.1.178:8001"

# Copyright
copyright: "&copy; 2021 Havenstad"

# Repository
repo_name: "havenstadrp/documentatie"
repo_url: "https://github.com/havenstadrp/documentatie"
edit_uri: "edit/main/docs/"

# Configuration
docs_dir: "docs"


theme:
  name: "material"

  language: "nl"

#   shortcuts:
#     help: 191 # ?
#     next: 78 # n
#     previous: 80 # p
#     search: 83 # s

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  logo: "assets/images/logo.png"
  favicon: "assets/images/favicon.ico"

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.prune
    - navigation.top
    - search.suggest
    - search.share
    - header.autohide
    - content.code.annotate

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search:
      lang: nl
      separator: '[\s\-\.]'

# Page tree
nav:
  - "ðŸ  Havenstad": "index.md"
  - "ðŸ’¼ Jobs":
    - "ðŸš‘ Ambulance": "guide/jobs/ambulance.md"
    - "ðŸšŒ Bus": "guide/jobs/bus.md"
    - "ðŸŒ­ Hotdog": "guide/jobs/hotdog.md"
    - "ðŸ“° Nieuws": "guide/jobs/nieuws.md"
    - "ðŸ‘® Politie": "guide/jobs/politie.md"
    - "ðŸ›» Takeldienst": "guide/jobs/takeldienst.md"
    - "ðŸš• Taxi": "guide/jobs/taxi.md"
    - "ðŸšš Trucker": "guide/jobs/trucker.md"
    - "ðŸ”§ VAB": "guide/jobs/vab.md"
    - "ðŸš› Vuilniswagen": "guide/jobs/vuilniswagen.md"
    - "â›ï¸ Mijnen": "guide/jobs/mijnen.md"
    - "ðŸŒ® Taco": "guide/jobs/taco.md"
    - "ðŸŸ Vissen": "guide/jobs/vissen.md"
    - "ðŸ‡ Wijngaard": "guide/jobs/wijngaard.md"
    - "ðŸ§‘â€ðŸŒ¾ Landbouw": "guide/jobs/landbouw.md"
    - "ðŸ¤¿ Duiken": "guide/jobs/duiken.md"
    - "ðŸ‘” Management": "guide/jobs/management.md"
    - "ðŸª™ Metaaldetector": "guide/jobs/metaaldetector.md"
  - "ðŸ’¸ FinanciÃ«l":
    - "ðŸ¦ Bank": "guide/financieel/bank.md"
    - "ðŸª™ Crypto": "guide/financieel/crypto.md"
    - "ðŸ¤‘ Pawnshop": "guide/financieel/pawnshop.md"
  - "ðŸ§ Character":
    - "ðŸ¤ª Character": "guide/character/character.md"
    - "ðŸ”„ Command binding": "guide/character/commandbinding.md"
    - "ðŸ•º Emotes": "guide/character/emotes.md"
    - "âž• Extra": "guide/character/extra.md"
    - "âŒš Fitbit": "guide/character/fitbit.md"
    - "ðŸ“Ÿ HUD": "guide/character/hud.md"
    - "ðŸ• Huisdier": "guide/character/huisdier.md"
    - "ðŸŽ’ Inventory": "guide/character/inventory.md"
    - "ðŸ‘• Kledij": "guide/character/kledij.md"
    - "ðŸ–¨ï¸ Printer": "guide/character/printer.md"
    - "â­• Radialmenu": "guide/character/radialmenu.md"
    - "ðŸ—ºï¸ Spawn": "guide/character/spawn.md"
    - "ðŸ§Žâ€â™€ï¸ Strippers": "guide/character/strippers.md"
    - "ðŸ‘ï¸ Target": "guide/character/target.md"
    - "ðŸ“± Telefoon": "guide/character/telefoon.md"
  - "ðŸŽ° Casino":
    - "ðŸƒ Blackjack": "guide/casino/blackjack.md"
    - "â˜¸ï¸ Luckywheel": "guide/casino/luckywheel.md"
    - "ðŸ‡ Paarden": "guide/casino/paarden.md"
    - "ðŸª© Roulette": "guide/casino/roulette.md"
    - "ðŸŽ° Slots": "guide/casino/slots.md"
  - "ðŸŒ‡ Gebouwen":
    - "ðŸ¢ Stadhuis": "guide/gebouwen/stadhuis.md"
    - "ðŸª Winkel": "guide/gebouwen/winkels.md"
    - "ðŸ¡ Wonen": "guide/gebouwen/wonen.md"
  - "â˜ ï¸ Onderwereld":
    - "âš—ï¸ Drugs": "guide/onderwereld/drugs.md"
    - "ðŸ” Gevangenis": "guide/onderwereld/gevangenis.md"
    - "â›“ï¸ Kidnappen": "guide/onderwereld/kidnap.md"
    - "ðŸª› Lockpick": "guide/onderwereld/lockpick.md"
    - "ðŸ¤‘ Verkopen": "guide/onderwereld/verkopen.md"
    - "ðŸ”« Wapens": "guide/onderwereld/wapens.md"
    - "ðŸ§¹ Werkstraf": "guide/onderwereld/werkstraf.md"
    - "Overvallen":
      - "ðŸ’° Bank": "guide/onderwereld/overvallen/bank.md"
      - "ðŸ”« Huis": "guide/onderwereld/overvallen/huis.md"
      - "ðŸŽ iFruit": "guide/onderwereld/overvallen/ifruit.md"
      - "ðŸ’Ž Juwelier": "guide/onderwereld/overvallen/juwelier.md"
      - "ðŸšš Truck": "guide/onderwereld/overvallen/truck.md"
      - "ðŸª Winkel": "guide/onderwereld/overvallen/winkel.md"
  - "ðŸ’¾ Server":
    - "ðŸ“Š Info": "guide/server/info.md"
    - "âŒ¨ï¸ Commando's": "guide/server/commands.md"
  - "ðŸš˜ Voertuigen":
    - "ðŸš— Voertuig": "guide/voertuigen/voertuig.md"
    - "ðŸŽï¸ Autowinkel": "guide/voertuigen/autowinkel.md"
    - "ðŸ…¿ï¸ Garages": "guide/voertuigen/garages.md"
    - "ðŸ Racen": "guide/voertuigen/racen.md"
    - "ðŸ”‹ Sloperij": "guide/voertuigen/sloperij.md"
    - "ðŸŽ¨ Tuning": "guide/voertuigen/tuning.md"


extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics: Custom name
    actions:
      - accept
      - manage

  version:
    provider: mike

  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/kYTDZc5mnG
      name: Havenstad Discord
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCnDHClzKX1bgx8h2JW_Oa_A
      name: Havenstad youtube kanaal
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/havenstadrp
      name: Havenstad Facebook

  generator: false

copyright: Copyright &copy; 2020 - 2022 Havenstad
